### ISSUE TITLE
Connect to Twitch IRC channel

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/twitch-chat-stats#1]
Refference: https://github.com/justintv/Twitch-API/blob/master/IRC.md

Maybe this can help: 

> Made my irc stats @meteorjs project faster and mobile friendly. Love watching real time updates on a mobile browser.  http://meteor_irc.meteor.com/

https://github.com/waartaa/waartaa
https://github.com/martynsmith/node-irc
https://github.com/Pent/meteor-irc

**Comment by mhammerc** [comment]
Done. I'm now able to connect to a channel then to speak inside it ! And more, it work fast !

**Comment by shtefcs** [comment]
Super! Closing
