### ISSUE TITLE
Get some data

### ISSUE THREAD

**Issue by shtefcs** [vanila-io/twitch-chat-stats#2]
- [x] Get number of messages
- [x] Chat speed (messages per second/minute )
- [x] Most popular `keyword` / `message`
- [ ] Get number of deleted messages `<message deleted>`
- [x] Most popular speaker

**Comment by mhammerc** [comment]
Also this ?
-  Most popular speaker

**Comment by shtefcs** [comment]
That is interesting. What you mean by that ? The user who sent most messages in some period ?

**Comment by mhammerc** [comment]
Yes that's it :p !

**Comment by shtefcs** [comment]
Nice idea, lets do it .

**Comment by mhammerc** [comment]
I can't find how to get deleted message because the user send his message, our server receive it then the message is deleted on twitch chat. I'm not sure it is on the irc ?

**Comment by shtefcs** [comment]
I see. Well, then we can leave that out.

**Comment by mhammerc** [comment]
so we're done here i think for the moment

**Comment by shtefcs** [comment]
yep, a closing.
