### ISSUE TITLE
the stats acquisition

### ISSUE THREAD

**Issue by mhammerc** [vanila-io/twitch-chat-stats#5]
This issue is a little bit technical but may be interesting. **How do we collect stats ?**
Stats are new to me and i'm happy to get deeper in it.

Here is my proposal. First we have the stats layer who acquire and save datas :
- We collect the stats in normal way for 10 minutes (number to debate)
- After the 10 minutes, we store them into database then flush (delete) all stats in the temp memory

And, in that way we can then create an other layer, the user layer. The user layer read and transpile data into readable data and send them to the client (in a realtime way ofc). That mean that when viewing charts, or history or realtime data we can not be more precise than 10 minutes. Maybe we have to down that number to 60 seconds by example ?

**Comment by mhammerc** [comment]
I'll make that number editable in all ways (not dynamically but at startup)

**Comment by shtefcs** [comment]
If I am getting right,  you are saying that we are showing stats based on last 10 minutes ? Like most popular keyword in last 10 min ?

If its true, yes that should be editable so we can test it out.

Still confusing about data storing, but I will think about it today.

You can do it on your own some MVP.

**Comment by mhammerc** [comment]
Okay, it's coded. I set the timeout (time before saving to database) to 60 seconds

**Comment by mhammerc** [comment]
Done for an interval of 60 seconds.
